// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc746.Robot7462018.subsystems;

import org.usfirst.frc746.Robot7462018.Robot;
import org.usfirst.frc746.Robot7462018.RobotMap;
import org.usfirst.frc746.Robot7462018.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Arm extends Subsystem {


    private final SpeedController armMotor = RobotMap.armarmMotor;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    	setDefaultCommand(new armControl());
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void stop() {
    	armMotor.set(0);
    }
    
    public void setArmMotor(double speed) {
		if (speed > 1 || speed < -1) {
			System.out.println("WARNING! Unsafe speeds");
		} 
		
		else {
			armMotor.set(speed);
		}
	}
    
    public void armJoysticks(Joystick arm) {
    	armMotor.set(Robot.oi.operator2.getY());
    }

	public double getIntakeMotor() {
		return armMotor.get();
	}
}

